### ISSUE TITLE
Worgen zone

### ISSUE THREAD

**Issue by hguy23** [SkyFireArchives/SkyFireDB#44] opened 2012-03-04 08:34 UTC
When you create so I can not see Worgen quests or npc why?

**Comment by Bootz** [comment] 2012-03-04 09:10
ummm. your running what?
o/s?
db?
core rev?
addons?

this info can come in handy. in diagnosing, the issue.

make sure your using the newest pull of core, and newest release of sfdb.

im closing this, too much missing into on the problem... create a proper bug track and this will keep it from being closed.

**Closed as completed by Bootz** 2012-03-04 09:10 UTC

**Comment by hguy23** [comment] 2012-03-04 09:11
I using a Windows 2008
Skyfire Database latest
Skyfire core latest 
Addons - i not using

**Comment by Raydeon** [comment] 2012-03-05 16:43
You also need to make sure you have used the latest skyfire patcher for your wow.exe. The symptoms you discribe are often experienced by people that have not properly patched their wow.exe. The latest can be found here: https://github.com/ProjectSkyfire/SkyFire-Community-Tools

Raydeon

**Comment by hguy23** [comment] 2012-03-07 06:19
I have this

**Comment by Raydeon** [comment] 2012-03-08 21:31
Unfortunately... I do not have windows 8, so I cannot reproduce your issue. However, 99.9% of the time, (unless you are running a Mac), if you cannot see npcs, or take quests, or loot anything, it is because you have NOT properly patched your wow.exe. Again, the latest patcher can be found here: https://github.com/ProjectSkyfire/SkyFire-Community-Tools . Even if you had a patched wow.exe from before, you NEED to repatch for the rebase core. Other notes.... you HAVE to have a wow client patched to 4.0.6a... also, did you verify your database installed properly? Sounds silly, I know... but shit happens.

Raydeon
